// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
    process.env.SUPABASE_URL ||
      process.env.PRISMA_URL ||
      process.env.DATABASE_URL,
  },
});
